stages:
    - staging

staging:
    image: python:3.8
    stage: staging
    script:
        - apt-get update -qy
        - apt-get install -y build-essential cmake
        - mkdir -p build
        - cd build
        - cmake "-DCMAKE_BUILD_TYPE=Release" ..
        - make
        - test/cpu/cpu_unit_test
